[project]
name = "Playthrough 3"
version = "2.3.0"
authors = [{ name = "keogh" }]
description = "Adds PT3 with listed named enemies/bosses fixed at 71, ordinary enemies 69 to 69 + spread, and level-1 cash prices and rewards. Default spread 3: 69/70/71/72 at 5/20/55/20%. Full spread odds available in the in-game description. Supports BL1 Enhanced."

[tool.sdkmod]
name = "Playthrough 3"
mod_type = "Standard" # or "Library"
supported_games = ["BL1", "BL1E"]
coop_support = "Unknown"
auto_enable = true
license = {name = "GPL3", url = "https://choosealicense.com/licenses/gpl-3.0/" }
